function [mem_CJ , mem_deriv_propag_high , mem_deriv_propag_low , time_comp_CJ] ...
    = CTCR_Deriv_Propag(...
    bool_J , bool_Cs0 , ctcr_carac , ctcr_construc , ctcr_act , ctcr_load , mem_bvp , bvp_prop , simulation_param , local_mem_deriv_propag_low , bool_disp_terminal)


% EXPLAIN THE FUNCTIONS
%
%
%
%
%
    
    [mem_deriv_propag_low , mem_deriv_propag_high , mem_CJ] ...
    = Deriv_Propag_Init_Mem(...
    ctcr_carac , ctcr_construc , local_mem_deriv_propag_low , bvp_prop , simulation_param) ;
    
    [mem_CJ , mem_deriv_propag_high , mem_deriv_propag_low , time_comp_CJ] ...
    = Deriv_Propag_Int(...
    bool_J , bool_Cs0 , ctcr_construc , ctcr_carac , ctcr_act , ctcr_load , mem_bvp , bvp_prop , simulation_param , ...
    mem_deriv_propag_low , mem_deriv_propag_high , mem_CJ , bool_disp_terminal) ;
    
end